spring:
  application:
    name: Vero
  datasource:
    url: jdbc:h2:mem:vero
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Gemini AI Configuration
gemini:
  api-key: ${GEMINI_API_KEY:AIzaSyAVLJZx9xWavI4UhuUOWO6KjFiEQVKIpMk}
  base-url: https://generativelanguage.googleapis.com/v1beta
  model: gemini-flash-lite-latest
  temperature: 0.3
  max-output-tokens: 50000